# Custom Language File for Launcher Customizer

[ejs.app]
title = "Zmoon"

[ejs.landing]
mediaGitHubURL = "https://github.com/ZellOffe/Zmoon"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zwork"

[ejs.settings]
sourceGithubLink = "https://github.com/ZellOffe/Zmoon"
supportLink = "https://github.com/ZellOffe/Zmoon/issue"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Zmoon Launcher"
welcomeDescription = "🌙 zMOON Cobblemon - L'aventure Pokémon ultime sur Minecraft !
Plonge dans zMOON Cobblemon, un serveur Minecraft unique qui mélange l'exploration, la survie et le mod Cobblemon pour une expérience Pokémon immersive !

🔹 Un monde vaste et dynamique – Explore des biomes variés, capture des Cobblemon et affronte d'autres dresseurs.
🔹 Système de ligue Pokémon – Défis des champions, affronte l'Élite 4 et prouve ta valeur !
🔹 Quêtes et événements spéciaux – Participe à des aventures scénarisées et gagne des récompenses exclusives.
🔹 Un gameplay optimisé – Économie, métiers, tournois PvP et bien plus encore.
🔹 Une communauté active – Rejoins des clans, échange tes Cobblemon et partage ton aventure avec d'autres dresseurs.

💠 Rejoins-nous et deviens le meilleur dresseur ! 💠"
welcomeDescCTA = "Vous êtes à quelques clics de Zmoon."
